# =============================================================================
# AmbientBird.gd
# A bird that flies across the map. Spawned in flocks by AmbientLayer.
# Five distinct species so mixed flocks look colourful. Each type has its own
# 9-frame wing-flap animation generated by PixelLab.
# Falls back to the V-line silhouette if textures are missing.
# =============================================================================
class_name AmbientBird
extends Node2D

const Balance = preload("res://scripts/BalanceConfig.gd")

enum BirdType { DARK, BLUE_JAY, RED_ROBIN, YELLOW_CANARY, GREEN_PARAKEET }

const _TEX_DIR := {
	BirdType.DARK:           "res://resources/environment/ambient/bird/dark/",
	BirdType.BLUE_JAY:       "res://resources/environment/ambient/bird/blue_jay/",
	BirdType.RED_ROBIN:      "res://resources/environment/ambient/bird/red_robin/",
	BirdType.YELLOW_CANARY:  "res://resources/environment/ambient/bird/yellow_canary/",
	BirdType.GREEN_PARAKEET: "res://resources/environment/ambient/bird/green_parakeet/",
}

# DARK sprites are 32x32; coloured sprites are 64x64 — scale to ~48px visual.
const _SPRITE_SCALE := {
	BirdType.DARK:           1.5,
	BirdType.BLUE_JAY:       0.75,
	BirdType.RED_ROBIN:      0.75,
	BirdType.YELLOW_CANARY:  0.75,
	BirdType.GREEN_PARAKEET: 0.75,
}

# Some sprites were generated facing left; flip logic is inverted for those.
const _BASE_FLIP := {
	BirdType.DARK:           false,
	BirdType.BLUE_JAY:       false,
	BirdType.RED_ROBIN:      true,
	BirdType.YELLOW_CANARY:  false,
	BirdType.GREEN_PARAKEET: false,
}

const _FRAME_COUNT := 9

var bird_type:   BirdType = BirdType.DARK
var velocity_x:  float    = 0.0
var _despawn_x:  float    = 0.0
var _flap_phase: float    = 0.0   # drives the shadow pulse only
var _anim:       AnimatedSprite2D = null
var _has_tex:    bool     = false

func setup(start_pos: Vector2, dir: int, max_distance: float = 1800.0,
		btype: BirdType = BirdType.DARK) -> void:
	bird_type       = btype
	global_position = start_pos
	velocity_x      = float(dir) * randf_range(Balance.AMBIENT_BIRD_SPEED_MIN,
			Balance.AMBIENT_BIRD_SPEED_MAX)
	_despawn_x      = start_pos.x + float(dir) * max_distance
	_flap_phase     = randf() * TAU
	z_index         = Balance.AMBIENT_BIRD_Z

	_anim          = AnimatedSprite2D.new()
	var s: float   = _SPRITE_SCALE[bird_type]
	_anim.scale    = Vector2(s, s)
	_anim.flip_h   = _BASE_FLIP[bird_type] != (dir < 0)
	add_child(_anim)
	_build_sprite_frames()
	if _has_tex:
		_anim.play("fly")

func _build_sprite_frames() -> void:
	var dir: String = _TEX_DIR[bird_type]
	for i in _FRAME_COUNT:
		if not ResourceLoader.exists(dir + "fly_%d.png" % i):
			return
	var sf := SpriteFrames.new()
	sf.remove_animation("default")
	sf.add_animation("fly")
	sf.set_animation_speed("fly", 12.0)
	sf.set_animation_loop("fly", true)
	for i in _FRAME_COUNT:
		sf.add_frame("fly", load(dir + "fly_%d.png" % i))
	_anim.sprite_frames = sf
	_has_tex = true

func _process(delta: float) -> void:
	global_position.x += velocity_x * delta
	_flap_phase       += delta * Balance.AMBIENT_BIRD_FLAP_RATE
	queue_redraw()
	if (velocity_x > 0 and global_position.x > _despawn_x) \
			or (velocity_x < 0 and global_position.x < _despawn_x):
		queue_free()

func _draw() -> void:
	var lift: float = (sin(_flap_phase) + 1.0) * 0.5
	var rx: float   = Balance.AMBIENT_BIRD_SHADOW_RADIUS_X * (1.0 + lift * 0.25)
	var ry: float   = Balance.AMBIENT_BIRD_SHADOW_RADIUS_Y * (1.0 + lift * 0.25)
	var shadow_col  := Color(0.03, 0.03, 0.05, 0.32 - lift * 0.10)
	var pts := PackedVector2Array()
	for i in 16:
		var a: float = TAU * float(i) / 16.0
		pts.append(Vector2(cos(a) * rx,
				Balance.AMBIENT_BIRD_SHADOW_OFFSET_Y + sin(a) * ry))
	draw_colored_polygon(pts, shadow_col)

	if _has_tex:
		return
	# Fallback V-line silhouette when textures are missing.
	var flap: float = sin(_flap_phase) * 5.0
	var fp := PackedVector2Array([
		Vector2(-10, flap), Vector2(-3, 0), Vector2(3, 0), Vector2(10, flap),
	])
	if velocity_x < 0:
		for i in fp.size():
			fp[i] = Vector2(-fp[i].x, fp[i].y)
	draw_polyline(fp, Balance.AMBIENT_BIRD_BODY_COLOR, 2.0)
